# -*- coding: utf-8 -*-
"""Only_BSE_Stocks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iBmfcR5effRxNB2Z11KMqUayaeJI8ZeL
"""

import pandas as pd

# Load BSE and NSE stock lists from CSV files
bse_stocks_df = pd.read_csv('/content/Equity.csv')  # Replace with the actual path to your BSE CSV file
nse_stocks_df = pd.read_csv('/content/NSE_stocks.csv')  # Replace with the actual path to your NSE CSV file


# We'll use 'Security Code' for this example
bse_stock_codes = bse_stocks_df['Security Code'].astype(str)  # Convert to string to avoid type mismatch
nse_stock_codes = nse_stocks_df['SYMBOL'].astype(str)

# Find stocks that are in BSE but not in NSE
bse_only_stocks = bse_stocks_df[~bse_stocks_df['Security Code'].isin(nse_stock_codes)]

# Display the result
print("Stocks present in BSE but not in NSE:")
print(bse_only_stocks)

# Optionally, save the result to a new CSV file
bse_only_stocks.to_csv('bse_only_stocks.csv', index=False)